{% set versions = {
    "8.3.12": "c1a33aa5fa15e6b70d7946ce6d237246842887ec84ea0b35dfc2535c868a2770"
} %}


{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "pythia")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://gitlab.com/Pythia8/releases/-/archive/pythia8312/releases-pythia{{ version|replace(".", "") }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('gfortran') }}
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make
    
  run_constrained:
    - pythia8 <0

about:
  home: "https://pythia.org"
  license: "GPL-3.0"
  summary: "PYTHIA is a program for the generation of high-energy physics collision events, i.e. for the description of collisions at high energies between electrons, protons, photons and heavy nuclei."

extra:
  recipe-maintainers:
    - meiyasan
